FROM node:18
WORKDIR /app

# install deps (cached)
COPY package*.json ./
RUN npm install

# copy rest of the app
COPY . .

EXPOSE 5173

# start vite dev server with hot reload
CMD ["npm", "run", "dev"]
